<a href="https://colab.research.google.com/github/internship-kaard/zenteiq-kaard/blob/main/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Develop a machine learning model that can predict student dropout rates or academic success based on a variety of factors, such as attendance, grades, and demographic data. The model should be able to identify students who are at risk of dropping out or falling behind and provide targeted interventions and support.

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
import math
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.multiclass import OneVsOneClassifier


In [ ]:
#data loading
df = pd.read_csv('dataset.csv')
#view the data
df.head()

Marital status  Application mode  Application order  Course  Daytime/evening attendance  \
0               1                17                  5     171                           1   
1               1                15                  1    9254                           1   
2               1                 1                  5    9070                           1   
3               1                17                  2    9773                           1   
4               2                39                  1    8014                           0   

   Previous qualification  Previous qualification (grade)  Nacionality  Mother's qualification  \
0                       1                           122.0            1                      19   
1                       1                           160.0            1                       1   
2                       1                           122.0            1                      37   
3                       1                           122.0            1                      38   
4                       1                           100.0            1                      37   

   Father's qualification  ...  Curricular units 2nd sem (credited)  \
0                      12  ...                                    0   
1                       3  ...                                    0   
2                      37  ...                                    0   
3                      37  ...                                    0   
4                      38  ...                                    0   

   Curricular units 2nd sem (enrolled)  Curricular units 2nd sem (evaluations)  \
0                                    0                                       0   
1                                    6                                       6   
2                                    6                                       0   
3                                    6                                      10   
4                                    6                                       6   

   Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
0                                    0                              0.00   
1                                    6                             13.67   
2                                    0                              0.00   
3                                    5                             12.40   
4                                    6                             13.00   

   Curricular units 2nd sem (without evaluations)  Unemployment rate  Inflation rate   GDP  \
0                                               0               10.8             1.4  1.74   
1                                               0               13.9            -0.3  0.79   
2                                               0               10.8             1.4  1.74   
3                                               0                9.4            -0.8 -3.12   
4                                               0               13.9            -0.3  0.79   

     Target  
0   Dropout  
1  Graduate  
2   Dropout  
3  Graduate  
4  Graduate  

[5 rows x 37 columns]

In [ ]:
#finding null and duplicates
df.isna().sum()
df.duplicated().sum()

0

In [ ]:
#EDA - Exploratory Data Analysis
print(df.shape)

(4424, 37)


In [ ]:
##basic information of data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4424 entries, 0 to 4423
Data columns (total 37 columns):
 #   Column                                          Non-Null Count  Dtype  
---  ------                                          --------------  -----  
 0   Marital status                                  4424 non-null   int64  
 1   Application mode                                4424 non-null   int64  
 2   Application order                               4424 non-null   int64  
 3   Course                                          4424 non-null   int64  
 4   Daytime/evening attendance                      4424 non-null   int64  
 5   Previous qualification                          4424 non-null   int64  
 6   Previous qualification (grade)                  4424 non-null   float64
 7   Nacionality                                     4424 non-null   int64  
 8   Mother's qualification                          4424 non-null   int64  
 9   Father's qualification                   

In [ ]:
##describe the data
from pandas.io.formats.format import set_option
set_option('display.precision',2)
df.describe()

Marital status  Application mode  Application order   Course  Daytime/evening attendance  \
count         4424.00           4424.00            4424.00  4424.00                     4424.00   
mean             1.18             18.67               1.73  8856.64                        0.89   
std              0.61             17.48               1.31  2063.57                        0.31   
min              1.00              1.00               0.00    33.00                        0.00   
25%              1.00              1.00               1.00  9085.00                        1.00   
50%              1.00             17.00               1.00  9238.00                        1.00   
75%              1.00             39.00               2.00  9556.00                        1.00   
max              6.00             57.00               9.00  9991.00                        1.00   

       Previous qualification  Previous qualification (grade)  Nacionality  \
count                 4424.00                         4424.00      4424.00   
mean                     4.58                          132.61         1.87   
std                     10.22                           13.19         6.91   
min                      1.00                           95.00         1.00   
25%                      1.00                          125.00         1.00   
50%                      1.00                          133.10         1.00   
75%                      1.00                          140.00         1.00   
max                     43.00                          190.00       109.00   

       Mother's qualification  Father's qualification  ...  \
count                 4424.00                 4424.00  ...   
mean                    19.56                   22.28  ...   
std                     15.60                   15.34  ...   
min                      1.00                    1.00  ...   
25%                      2.00                    3.00  ...   
50%                     19.00                   19.00  ...   
75%                     37.00                   37.00  ...   
max                     44.00                   44.00  ...   

       Curricular units 1st sem (without evaluations)  Curricular units 2nd sem (credited)  \
count                                         4424.00                              4424.00   
mean                                             0.14                                 0.54   
std                                              0.69                                 1.92   
min                                              0.00                                 0.00   
25%                                              0.00                                 0.00   
50%                                              0.00                                 0.00   
75%                                              0.00                                 0.00   
max                                             12.00                                19.00   

       Curricular units 2nd sem (enrolled)  Curricular units 2nd sem (evaluations)  \
count                              4424.00                                 4424.00   
mean                                  6.23                                    8.06   
std                                   2.20                                    3.95   
min                                   0.00                                    0.00   
25%                                   5.00                                    6.00   
50%                                   6.00                                    8.00   
75%                                   7.00                                   10.00   
max                                  23.00                                   33.00   

       Curricular units 2nd sem (approved)  Curricular units 2nd sem (grade)  \
count                              4424.00                           4424.00   
mean                                  4.44                             

In [ ]:
##histogram
sns.set_theme(style = 'darkgrid')
df.hist(bins=10, figsize=(50, 35), grid=True, legend=None);

In [100]:
##finding unique values
# list(df)
for col in list(df):
  print(col)
  print(df[col].unique())

Marital status
[1 2 4 3 5 6]
Application mode
[17 15  1 39 18 53 44 51 43  7 42 16  5  2 10 57 26 27]
Application order
[5 1 2 4 3 6 9 0]
Course
[ 171 9254 9070 9773 8014 9991 9500 9238 9670 9853 9085 9130 9556 9147
 9003   33 9119]
Daytime/evening attendance
[1 0]
Previous qualification
[ 1 19 42 39 10  3 40  2  4 12 43 15  6  9 38  5 14]
Previous qualification (grade)
[122.  160.  100.  133.1 142.  119.  137.  138.  139.  136.  133.  110.
 149.  127.  135.  140.  125.  126.  151.  115.  150.  143.  130.  120.
 103.  154.  132.  167.  129.  141.  116.  148.  118.  106.  121.  114.
 124.  123.  113.  111.  131.  158.  146.  117.  153.  178.   99.  134.
 128.  170.  155.  145.  152.  112.  107.  156.  188.   96.  161.  166.
 147.  144.  102.  101.  180.  172.  105.  108.  165.  190.  162.  164.
 163.  159.  117.4 175.  133.8 176.  168.  139.3  97.  157.  140.8 184.4
 148.9 109.  174.  182.  138.6  95.  154.4 163.3 145.7 123.9 124.4 169.
 177.  138.7 119.1 118.9 126.6]
Nacionality
[  1  

In [ ]:
df['Target'].unique()

array(['Dropout', 'Graduate', 'Enrolled'], dtype=object)

In [ ]:
df.loc[:,'Target'].value_counts()

Graduate    2209
Dropout     1421
Enrolled     794
Name: Target, dtype: int64

In [ ]:
df['Marital status'].unique()

array([1, 2, 4, 3, 5, 6])

In [ ]:
df.loc[:,'Marital status'].value_counts()

1    3919
2     379
4      91
5      25
6       6
3       4
Name: Marital status, dtype: int64

In [ ]:
df.loc[:,'Gender'].value_counts()

0    2868
1    1556
Name: Gender, dtype: int64

In [101]:
df.loc[:,'Course'].value_counts()

9500    766
9147    380
9238    355
9085    337
9773    331
9670    268
9991    268
9254    252
9070    226
171     215
8014    215
9003    210
9853    192
9119    170
9130    141
9556     86
33       12
Name: Course, dtype: int64

In [ ]:
df.columns

Index(['Marital status', 'Application mode', 'Application order', 'Course',
       'Daytime/evening attendance', 'Previous qualification', 'Previous qualification (grade)',
       'Nacionality', 'Mother's qualification', 'Father's qualification', 'Mother's occupation',
       'Father's occupation', 'Admission grade', 'Displaced', 'Educational special needs',
       'Debtor', 'Tuition fees up to date', 'Gender', 'Scholarship holder', 'Age at enrollment',
       'International', 'Curricular units 1st sem (credited)',
       'Curricular units 1st sem (enrolled)', 'Curricular units 1st sem (evaluations)',
       'Curricular units 1st sem (approved)', 'Curricular units 1st sem (grade)',
       'Curricular units 1st sem (without evaluations)', 'Curricular units 2nd sem (credited)',
       'Curricular units 2nd sem (enrolled)', 'Curricular units 2nd sem (evaluations)',
       'Curricular units 2nd sem (approved)', 'Curricular units 2nd sem (grade)',
       'Curricular units 2nd sem (without e

In [ ]:
#continuous
features = df[['previous qualification', 'Admission grade', 'Displaced', 'Tuition fees up to date', 'Scholarship holder', 'Age at enrollment', 'Curricular units 1st sem (credited)', 'Curricular units 1st sem (enrolled)', 'Curricular units 1st sem (evaluations)', 'Curricular units 1st sem (approved)', 'Curricular units 1st sem (grade)', 'Curricular units 1st sem (without evaluations)', 'Curricular units 2nd sem (credited)', 'Curricular units 2nd sem (enrolled)', 'Curricular units 2nd sem (evaluations)', 'Curricular units 2nd sem (approved)', 'Curricular units 2nd sem (grade)', 'Curricular units 2nd sem (without evaluations)', 'Unemployment rate', 'Inflation rate', 'GDP']]

In [ ]:
#categorical
features = df[['Marital status', 'Application order', 'Cours', 'Previous qualification', 'Nacionality', "Mother's qualification", "Father's qualification", "Mother's occupation", "Father's occupation", 'Educational special needs', 'Debtor', 'Gender']]

In [92]:
# Creating a copy of the dataset
s_df=df.copy() 

# Changing the Target to numerical Value 0 or 1. We are predicting if a Student is gonna Dropout or Graduate, ignoring the ones who are Enrolled.
s_df.replace("Dropout",1,inplace=True) 
s_df.replace("Graduate",0,inplace=True)
s_df.drop(s_df[s_df["Target"]=="Enrolled"].index,inplace=True)
s_df

Marital status  Application mode  Application order  Course  Daytime/evening attendance  \
0                  1                17                  5     171                           1   
1                  1                15                  1    9254                           1   
2                  1                 1                  5    9070                           1   
3                  1                17                  2    9773                           1   
4                  2                39                  1    8014                           0   
...              ...               ...                ...     ...                         ...   
4419               1                 1                  6    9773                           1   
4420               1                 1                  2    9773                           1   
4421               1                 1                  1    9500                           1   
4422               1                 1                  1    9147                           1   
4423               1                10                  1    9773                           1   

      Previous qualification  Previous qualification (grade)  Nacionality  Mother's qualification  \
0                          1                           122.0            1                      19   
1                          1                           160.0            1                       1   
2                          1                           122.0            1                      37   
3                          1                           122.0            1                      38   
4                          1                           100.0            1                      37   
...                      ...                             ...          ...                     ...   
4419                       1                           125.0            1                       1   
4420                       1                           120.0          105                       1   
4421                       1                           154.0            1                      37   
4422                       1                           180.0            1                      37   
4423                       1                           152.0           22                      38   

      Father's qualification  ...  Curricular units 2nd sem (credited)  \
0                         12  ...                                    0   
1                          3  ...                                    0   
2                         37  ...                                    0   
3                         37  ...                                    0   
4                         38  ...                                    0   
...                      ...  ...                                  ...   
4419                       1  ...                                    0   
4420                       1  ...                                    0   
4421                      37  ...                                    0   
4422                      37  ...                                    0   
4423                      37  ...                                    0   

      Curricular units 2nd sem (enrolled)  Curricular units 2nd sem (evaluations)  \
0                                       0                                       0   
1                                       6                                       6   
2                                       6                                       0   
3                                       6                                      10   
4                                       6                                       6   
...                                   ...                                     ...   
4419                                    6                                       8   
4420                                    6                  

In [94]:
s_df.loc[:,'Target'].value_counts()

0    2209
1    1421
Name: Target, dtype: int64

In [ ]:
#stacked bar chart


In [ ]:
##finding skewness
df.skew()

In [ ]:
# ##finding correlations between attributes
# df.corr(method='pearson')

In [ ]:
# ##correlation plot
# sns.heatmap(df.corr())

In [ ]:
# #kernal density estimate
# sns.set_theme(style = 'darkgrid')
# df['Marital status'].value_counts().plot(kind = 'kde');